name: Build
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        goarch: [amd64, arm64]
        goos: [darwin, windows, linux]
        go: ['1.22.x']
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Install dependencies
        run: go get .
      - name: Build ${{ matrix.goos }} ${{ matrix.goarch }}
        env:
          GOARCH: ${{ matrix.goarch }}
          GOOS: ${{ matrix.goos }}
        run: go build -v -o Mirror-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }} .
      - name: Upload Build Results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Mirror-${{ matrix.goos }}-${{ matrix.goarch }}
          path: Mirror*